---
- hosts: 127.0.0.1
  tasks:
    - name: Install packages
      dnf: name="{{ item }}" state=present
      become: true
      with_items:
        - nginx
        - jenkins
        - mock
        - git
        - openssh-server
        - pungi
        - rpm-sign
        - certbot
        - fedora-packager
        - fedpkg
        - fail2ban
        - fail2ban-server
        - iptables
        - dnf-automatic
        - mosh
        - vim
        # need to get anaconda install class for TigerOS possibly
        #- letsencrypt
