---
- hosts: 127.0.0.1
  tasks:
    - name: Add Docker CE repo
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      become: true
    - name: Install packages
      dnf: name="{{ item }}" state=present
      become: true
      with_items:
         base/management
        - git
        - openssh-server
        - fail2ban
        - fail2ban-server
        - iptables
        - dnf-automatic
        - python-firewall
        - certbot
        # these are personal pref tools - uncomment if desired
        # use ansible roles?
        - vim
    - name: Allow HTTPS (nginx)
      firewalld:
        service: https
        permanent: true
        state: enabled
    - name: Allow HTTP (nginx)
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Allow SSH access
      firewalld:
        service: ssh
        permanent: true
        state: enabled
    - name: Allow Cockpit
      firewalld:
        service: cockpit
        permanent: true
        state: enabled
    - name: Enable nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
    - name: Enable Cockpit service
      systemd:
        name: cockpit
        enabled: yes
        state: started
    - name: Enable sshd (openssh-server) service
      systemd:
        name: sshd
        enabled: yes
        state: started
    - name: Enable fail2ban service
      systemd:
        name: fail2ban
        enabled: yes
        state: started
    - name: Reload Firewall
      command: firewall-cmd --reload
      become: true
    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: Update packages
      command: dnf update
      become: true
    - name: Add certbot autorenewal
      cron: 
       name: "Certbot autorenew"
       user: "root"
       minute: "*"
       hour: "7"
       day: "19"
       month: "*"
       weekday: "*"
       job: "certbot-3 -q renew"
      
