---
- hosts: 127.0.0.1
  tasks:
    - name: Install packages
      dnf: name="{{ item }}" state=present
      become: true
      with_items:
        #base/management
        - git
        - openssh-server
        - fail2ban
        - fail2ban-server
        - iptables
        - dnf-automatic
        - python-firewall
        - certbot
        - vim
    - name: Allow HTTPS (nginx)
      firewalld:
        service: https
        permanent: true
        state: enabled
    - name: Allow HTTP (nginx)
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Allow SSH access
      firewalld:
        service: ssh
        permanent: true
        state: enabled
    - name: Allow Cockpit
      firewalld:
        service: cockpit
        permanent: true
        state: enabled
    - name: Enable nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
    - name: Enable Cockpit service
      systemd:
        name: cockpit
        enabled: yes
        state: started
    - name: Enable sshd (openssh-server) service
      systemd:
        name: sshd
        enabled: yes
        state: started
    - name: Enable fail2ban service
      systemd:
        name: fail2ban
        enabled: yes
        state: started
    - name: Reload Firewall
      command: firewall-cmd --reload
      become: true
    - name: Update packages
      command: dnf update --refresh -y
      become: true
    - name: Add certbot autorenewal
      cron: 
       name: "Certbot autorenew"
       user: "root"
       minute: "*"
       hour: "7"
       day: "19"
       month: "*"
       weekday: "*"
       job: "certbot-3 -q renew"
   - name: Add insync repo
      become: true
      copy:
       dest: /etc/nginx/nginx.conf
       mode: 0644
       owner: root
       group: root
       content: |
        # For more information on configuration, see:
        #   * Official English Documentation: http://nginx.org/en/docs/
        #   * Official Russian Documentation: http://nginx.org/ru/docs/

        user nginx;
        worker_processes auto;
        error_log /var/log/nginx/error.log;
        pid /run/nginx.pid;

        # Load dynamic modules. See /usr/share/nginx/README.dynamic.
        include /usr/share/nginx/modules/*.conf;

        events {
            worker_connections 1024;
        }
        http{
        server {
                listen 80;
                server_name builder.ritlug.com;
                root    /var/www/;
                # Load configuration files for the default server block.
                include /etc/nginx/default.d/*.conf;
                location / {
                        autoindex on;
                        autoindex_exact_size off;
                }

                error_page 404 /404.html;
                    location = /40x.html {
                }

                error_page 500 502 503 504 /50x.html;
                    location = /50x.html {
                }       
         
